apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-app-label
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-label
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "app label is required"
        pattern:
          metadata:
            labels:
              app: "?*"
